### ISSUE TITLE
Fix the icons to work with dark mode

### ISSUE THREAD

**Issue by ChandanShakya** [basnetsoyuj/basnetsoyuj#1]
## *Here change the icon to match with the dark mode.*
![Social Icons](https://user-images.githubusercontent.com/70548117/109504569-ca872d00-7ac3-11eb-88fc-35a229875860.png)

</br>
</br>
</br>

## *Also Here change the bash icon and flask icon.*
![language and Tools](https://user-images.githubusercontent.com/70548117/109504640-df63c080-7ac3-11eb-9cf4-0d6ac8afd6b7.png)

**Comment by basnetsoyuj** [comment]
Fixed with https://github.com/basnetsoyuj/basnetsoyuj/commit/4eb50377de3eab5ba2834dc368c50a2cee60bc32
